services:
  db:
    image: postgres:15-alpine
    container_name: nextjs_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    ports:
      - "5432:5432" # Это позволит подключаться к БД с вашего компьютера
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: